--- 
abstract: Traditional Chinese Calendar Implementation
author: (c) Copyright 2004-2007 Daisuke Maki <daisuke@endeworks.jp>.
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DateTime-Calendar-Chinese
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime::Event::Chinese: 0.05
  Math::Round: 0
  Params::Validate: 0
version: 0.07
